# Generated by Django 5.2 on 2025-04-08 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="watchlisted_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
