# Generated by Django 5.2 on 2025-04-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
